# Generated by Django 5.2.3 on 2025-06-17 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(help_text='Peso en kilogramos')),
                ('talla', models.FloatField(help_text='Talla en metros')),
                ('actividad_fisica', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=20)),
                ('enfermedades', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='usuarios.nino')),
            ],
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=100)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
