# Generated by Django 5.2.3 on 2025-06-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_historialclinico_logactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena')], max_length=20)),
                ('calorias', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('grasas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('grupo_alimenticio', models.CharField(max_length=50)),
                ('alergenos', models.JSONField()),
            ],
        ),
    ]
