# Generated by Django 5.2.3 on 2025-06-17 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('fuente', models.JSONField()),
                ('estado', models.CharField(default='vigente', max_length=20)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='usuarios.nino')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almuerzos', to='usuarios.alimento')),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almuerzos', to='usuarios.recomendacion')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionCena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenas', to='usuarios.alimento')),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenas', to='usuarios.recomendacion')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionDesayuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desayunos', to='usuarios.alimento')),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desayunos', to='usuarios.recomendacion')),
            ],
        ),
    ]
