# Generated by Django 5.2.3 on 2025-06-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_recomendacion_recomendacionalmuerzo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_min', models.IntegerField(help_text='Edad mínima en años')),
                ('edad_max', models.IntegerField(help_text='Edad máxima en años')),
                ('calorias', models.IntegerField()),
                ('proteinas', models.FloatField(help_text='Proteínas en gramos')),
                ('hierro', models.FloatField(help_text='Hierro en miligramos')),
                ('fuente', models.CharField(max_length=255)),
            ],
        ),
    ]
