# Generated by Django 5.2.3 on 2025-06-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_parametroreferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='alergenos_evitados',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='calorias_totales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='proteinas_totales',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
